
# 余白設定
[window]
padding = { x = 8, y = 6 }
dimensions = { columns = 140, lines = 40 }

[font]
size = 16
normal = { family = "Mononoki Nerd Font" }

[general]
import = [
  "~/.config/alacritty/themes/themes/wombat.toml",
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "tmux a -t default || { tmux new -s default -d && tmux source-file ~/.config/tmux/default.session.conf && tmux a -t default; }",
]
